"""
Run on Windows CI before PyInstaller.
Embeds all app source files as base64 into _rs_payload.py
"""
import base64, zipfile, io, os

root = os.path.dirname(__file__)
buf  = io.BytesIO()

with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
    skip = {'.git', '__pycache__', 'build', 'dist', '.github', 'installer'}
    for dirpath, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d not in skip]
        for f in files:
            if f.endswith(('.pyc', '.py')) and f not in ('build_payload.py',):
                # skip .py files that aren't app source
                rel = os.path.relpath(os.path.join(dirpath, f), root)
                if not rel.startswith('src') and not rel.startswith('assets'):
                    continue
            p   = os.path.join(dirpath, f)
            arc = os.path.relpath(p, root)
            if any(arc.startswith(s) for s in skip):
                continue
            if f.endswith('.pyc'):
                continue
            zf.write(p, arc)
            print(f'  + {arc}')

b64 = base64.b64encode(buf.getvalue()).decode('ascii')
out = os.path.join(root, '_rs_payload.py')
with open(out, 'w') as f:
    f.write('# Auto-generated by build_payload.py — do not edit\n')
    f.write(f'DATA = "{b64}"\n')

print(f'\nPayload: {len(buf.getvalue())//1024}KB -> {out}')
