"""
Run on Windows CI before PyInstaller.
Embeds ONLY the app source files as base64 into _rs_payload.py.
Strict whitelist: only src/*.py and assets/* are included.
Nothing else (no .ps1, no .cmd, no README, no LICENSE) is bundled.
"""
import base64, zipfile, io, os

root = os.path.dirname(os.path.abspath(__file__))
buf  = io.BytesIO()

# Strict whitelist — only these two directories are included
ALLOWED_PREFIXES = ("src" + os.sep, "assets" + os.sep)

# Extensions that are explicitly blocked regardless of directory
BLOCKED_EXTENSIONS = {
    ".ps1", ".cmd", ".bat", ".vbs", ".hta", ".wsf", ".js",
    ".pyc", ".pyo", ".pyd",
}

with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
    for dirpath, dirs, files in os.walk(root):
        # Never descend into these directories
        dirs[:] = [d for d in dirs if d not in {
            '.git', '__pycache__', 'build', 'dist',
            '.github', 'installer', 'node_modules',
        }]
        for fname in files:
            full_path = os.path.join(dirpath, fname)
            arc_path  = os.path.relpath(full_path, root)

            # Must be inside src/ or assets/
            if not any(arc_path.startswith(p) for p in ALLOWED_PREFIXES):
                continue

            # Block any suspicious extension
            ext = os.path.splitext(fname)[1].lower()
            if ext in BLOCKED_EXTENSIONS:
                continue

            zf.write(full_path, arc_path)
            print(f'  + {arc_path}')

payload_bytes = buf.getvalue()
b64 = base64.b64encode(payload_bytes).decode('ascii')
out = os.path.join(root, '_rs_payload.py')
with open(out, 'w') as f:
    f.write('# Auto-generated by build_payload.py — do not edit\n')
    f.write(f'DATA = "{b64}"\n')

print(f'\nPayload: {len(payload_bytes)//1024}KB ({len(b64)//1024}KB base64) -> {out}')
print(f'Files bundled: {len(buf.getvalue()) and sum(1 for _ in zipfile.ZipFile(io.BytesIO(payload_bytes)).namelist())}')
