"""
Reaction Studio v5 — Windows One-Click Installer
Self-contained .exe built by PyInstaller on Windows.
Embeds all app files via _rs_payload.py (generated by build_payload.py).
Shows a dark-themed tkinter GUI, extracts files, installs packages, creates shortcuts.

AV-CLEAN DESIGN:
  - Does NOT write .cmd, .vbs, .hta, .bat, or any script file to disk.
  - Shortcut points directly to pythonw.exe (built-in Windows Python, no console).
  - No wscript.exe, no ShellExecute tricks, no base64 shell commands.
"""
import sys, os, base64, zipfile, io, subprocess, threading, time
import tkinter as tk
from tkinter import ttk

import _rs_payload as _P
PAYLOAD_B64 = _P.DATA

APP_DIR    = os.path.join(os.environ.get("LOCALAPPDATA", "C:\\Users\\Public"), "ReactionStudio")
DESKTOP    = os.path.join(os.environ.get("USERPROFILE",  "C:\\Users\\Public"), "Desktop")
START_MENU = os.path.join(os.environ.get("APPDATA",      "C:\\Users\\Public"),
                          "Microsoft", "Windows", "Start Menu", "Programs", "Reaction Studio")

BG     = "#0f0f0f"
BG2    = "#1a0a2e"
ACCENT = "#7c3aed"
ACC2   = "#a855f7"
GREEN  = "#22c55e"
YELLOW = "#fbbf24"
RED    = "#ef4444"
TEXT   = "#f5f5f5"
DIM    = "#888888"


def _find_python() -> str:
    """
    Locate a real python.exe to launch the app with.
    
    IMPORTANT: When running as a PyInstaller .exe, sys.executable points to
    the installer .exe itself — NOT python.exe. We must never return that.
    We detect the PyInstaller bundle via sys.frozen and skip sys.executable.
    """
    import shutil

    candidates = []

    # 1. If NOT frozen (running as plain .py script), sys.executable is real python
    if not getattr(sys, "frozen", False):
        if sys.executable and os.path.isfile(sys.executable):
            exe = sys.executable
            if not exe.lower().endswith((".exe",)) or "python" in exe.lower():
                candidates.append(exe)

    # 2. Registry — where Windows records the Python install
    try:
        import winreg
        for root in (winreg.HKEY_LOCAL_MACHINE, winreg.HKEY_CURRENT_USER):
            for sub in (
                r"SOFTWARE\Python\PythonCore",
                r"SOFTWARE\WOW6432Node\Python\PythonCore",
            ):
                try:
                    with winreg.OpenKey(root, sub) as base_key:
                        i = 0
                        while True:
                            try:
                                ver = winreg.EnumKey(base_key, i)
                                with winreg.OpenKey(base_key, ver + r"\InstallPath") as ip:
                                    path = winreg.QueryValue(ip, None)
                                    for exe_name in ("pythonw.exe", "python.exe"):
                                        full = os.path.join(path, exe_name)
                                        if os.path.isfile(full):
                                            candidates.append(full)
                                i += 1
                            except OSError:
                                break
                except OSError:
                    pass
    except Exception:
        pass

    # 3. PATH
    for name in ("pythonw", "python", "python3"):
        found = shutil.which(name)
        if found and os.path.isfile(found):
            candidates.append(found)

    # 4. Common install locations
    import glob
    for pattern in [
        r"C:\Users\*\AppData\Local\Programs\Python\Python3*\pythonw.exe",
        r"C:\Users\*\AppData\Local\Programs\Python\Python3*\python.exe",
        r"C:\Python3*\pythonw.exe",
        r"C:\Python3*\python.exe",
        r"C:\Program Files\Python3*\pythonw.exe",
        r"C:\Program Files\Python3*\python.exe",
    ]:
        candidates.extend(glob.glob(pattern))

    # Filter: must be a real file and must NOT be this installer exe
    this_exe = os.path.abspath(sys.executable).lower()
    for c in candidates:
        c_abs = os.path.abspath(c).lower()
        if c_abs == this_exe:
            continue  # skip — this is the installer itself
        if os.path.isfile(c):
            return c   # return first valid hit

    return "python"   # absolute last resort — rely on PATH


def _create_shortcut(lnk_path: str, target_exe: str, args: str,
                     workdir: str, icon_path: str, description: str):
    """
    Create a Windows .lnk shortcut via PowerShell's WScript.Shell COM object.
    This is the standard, AV-clean way to create shortcuts from Python.
    target_exe and args are split so the shortcut TargetPath is a real executable
    (pythonw.exe), NOT wscript.exe or a script file.
    """
    # Escape single quotes inside the PS here-string
    def _esc(s): return s.replace("'", "''").replace('"', '`"')

    ps = (
        f"$ws = New-Object -ComObject WScript.Shell; "
        f"$s = $ws.CreateShortcut('{_esc(lnk_path)}'); "
        f"$s.TargetPath = '{_esc(target_exe)}'; "
        f"$s.Arguments = '{_esc(args)}'; "
        f"$s.WorkingDirectory = '{_esc(workdir)}'; "
        f"$s.Description = '{_esc(description)}'; "
        f"$s.IconLocation = '{_esc(icon_path)},0'; "
        f"$s.Save()"
    )
    subprocess.run(
        ["powershell", "-NoProfile", "-NonInteractive", "-Command", ps],
        capture_output=True
    )


class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Reaction Studio v5 — Setup")
        self.geometry("620x460")
        self.resizable(False, False)
        self.configure(bg=BG)
        self._done = False
        self._build_ui()

    # ── helpers ───────────────────────────────────────────────────────────────
    def _ui(self, fn):
        self.after(0, fn)

    def _log(self, msg):
        def _w():
            ts = time.strftime("%H:%M:%S")
            self._logtxt.config(state="normal")
            self._logtxt.insert("end", f"[{ts}]  {msg}\n")
            self._logtxt.see("end")
            self._logtxt.config(state="disabled")
        self._ui(_w)

    def _prog(self, pct, label=""):
        self._ui(lambda: (
            self._pbar.config(value=pct),
            self._plbl.config(text=label),
        ))

    def _step(self, idx, state, text):
        sym   = {"run": "▶", "ok": "●", "warn": "!", "fail": "✗"}[state]
        color = {"run": YELLOW, "ok": GREEN, "warn": YELLOW, "fail": RED}[state]
        self._ui(lambda s=sym, c=color, t=text, l=self._steps[idx]:
                 l.config(text=f"{s}  {t}", fg=c))

    # ── UI build ──────────────────────────────────────────────────────────────
    def _build_ui(self):
        # sidebar
        sb = tk.Frame(self, bg=BG2, width=178)
        sb.pack(side="left", fill="y")
        sb.pack_propagate(False)
        tk.Label(sb, text="⚡",       font=("Segoe UI", 48),          bg=BG2, fg=YELLOW).pack(pady=(58, 2))
        tk.Label(sb, text="REACTION", font=("Segoe UI", 13, "bold"),  bg=BG2, fg=YELLOW).pack()
        tk.Label(sb, text="STUDIO",   font=("Segoe UI", 13, "bold"),  bg=BG2, fg=TEXT).pack()
        tk.Label(sb, text="v5",       font=("Segoe UI", 10),          bg=BG2, fg="#a78bfa").pack(pady=(2, 18))
        for t in ["100% Local", "No API keys", "No subscriptions", "Runs forever"]:
            tk.Label(sb, text=t, font=("Segoe UI", 9), bg=BG2, fg=ACCENT).pack(pady=1)

        # main panel
        panel = tk.Frame(self, bg=BG)
        panel.pack(side="right", fill="both", expand=True, padx=24, pady=22)

        self._titlelbl = tk.Label(panel, text="Reaction Studio Setup",
                                  font=("Segoe UI", 17, "bold"), bg=BG, fg=TEXT)
        self._titlelbl.pack(anchor="w")
        self._sublbl = tk.Label(
            panel,
            text="Click Install to set up your local AI reaction video generator.",
            font=("Segoe UI", 10), bg=BG, fg=DIM, wraplength=400, justify="left")
        self._sublbl.pack(anchor="w", pady=(2, 14))

        self._steps = []
        for name in ["Extracting files", "Installing Python packages",
                     "Creating Desktop shortcut", "Adding to Start Menu",
                     "Registering app"]:
            lbl = tk.Label(panel, text=f"○  {name}", font=("Segoe UI", 10),
                           bg=BG, fg="#555555", anchor="w")
            lbl.pack(anchor="w", pady=2)
            self._steps.append(lbl)

        style = ttk.Style(self)
        style.theme_use("clam")
        style.configure("RS.Horizontal.TProgressbar",
                        troughcolor="#2a2a2a", background=ACCENT, thickness=7)
        self._pbar = ttk.Progressbar(panel, style="RS.Horizontal.TProgressbar",
                                     length=400, maximum=100)
        self._pbar.pack(anchor="w", pady=(12, 2))
        self._plbl = tk.Label(panel, text="", font=("Segoe UI", 9), bg=BG, fg=DIM)
        self._plbl.pack(anchor="w", pady=(0, 8))

        log_frame = tk.Frame(panel, bg="#0a0a0a", bd=1, relief="solid",
                             highlightbackground="#2a2a2a")
        log_frame.pack(fill="x", pady=(0, 14))
        self._logtxt = tk.Text(log_frame, bg="#0a0a0a", fg="#00ff88",
                               font=("Consolas", 8), height=6, bd=0, state="disabled")
        self._logtxt.pack(fill="x", padx=1, pady=1)

        row = tk.Frame(panel, bg=BG)
        row.pack(anchor="w")
        self._btngo = tk.Button(
            row, text="  ⚡  Install Now  ",
            font=("Segoe UI", 12, "bold"),
            bg=ACCENT, fg=TEXT, bd=0, activebackground=ACC2,
            cursor="hand2", padx=12, pady=7, command=self._start)
        self._btngo.pack(side="left")
        self._btnx = tk.Button(
            row, text="  Cancel  ",
            font=("Segoe UI", 10), bg="#1a1a1a", fg=RED, bd=0,
            cursor="hand2", padx=12, pady=7, command=self.destroy)
        self._btnx.pack(side="left", padx=10)

    # ── install ───────────────────────────────────────────────────────────────
    def _start(self):
        if self._done:
            main_py = os.path.join(APP_DIR, "src", "main.py")

            # Read the python path we saved during install — most reliable source
            _cfg = os.path.join(APP_DIR, "python_path.txt")
            python_exe = None
            if os.path.isfile(_cfg):
                try:
                    python_exe = open(_cfg).read().strip()
                    if not os.path.isfile(python_exe):
                        python_exe = None  # stale path — fall through
                except Exception:
                    python_exe = None

            # Fallback: search PATH
            if not python_exe:
                import shutil as _sh2
                python_exe = _sh2.which("pythonw") or _sh2.which("python") or "python"

            try:
                subprocess.Popen(
                    [python_exe, main_py],
                    cwd=os.path.join(APP_DIR, "src"),
                    creationflags=0x08000000,  # CREATE_NO_WINDOW
                )
            except Exception:
                # Last resort: shell=True lets Windows find python on its own
                subprocess.Popen(
                    f'start "" "{python_exe}" "{main_py}"',
                    shell=True,
                    cwd=os.path.join(APP_DIR, "src"),
                )
            self.destroy()
            return

        self._btngo.config(state="disabled")
        self._btnx.config(state="disabled")
        threading.Thread(target=self._worker, daemon=True).start()

    def _worker(self):
        # ── Step 0: Extract ───────────────────────────────────────────────
        self._step(0, "run", "Extracting files...")
        self._prog(3, "Decoding payload...")
        try:
            raw = base64.b64decode(PAYLOAD_B64)
            os.makedirs(APP_DIR, exist_ok=True)
            with zipfile.ZipFile(io.BytesIO(raw)) as zf:
                for entry in zf.infolist():
                    dst = os.path.join(APP_DIR, entry.filename)
                    if entry.filename.endswith("/"):
                        os.makedirs(dst, exist_ok=True)
                    else:
                        os.makedirs(os.path.dirname(dst), exist_ok=True)
                        with zf.open(entry) as src, open(dst, "wb") as out:
                            out.write(src.read())
            self._step(0, "ok", "Files extracted")
            self._log("Extracted all app files OK")
        except Exception as e:
            self._step(0, "fail", f"Extraction failed: {e}")
            self._log(f"ERROR: {e}")
            self._ui(lambda: (
                self._btngo.config(state="normal"),
                self._btnx.config(state="normal"),
            ))
            return
        self._prog(18, "Files extracted")

        # ── Step 1: Python packages ───────────────────────────────────────
        self._step(1, "run", "Installing Python packages (1–3 min)...")
        # Resolve the real python.exe path — works even inside a PyInstaller bundle
        # because we ask the OS where "python" lives, not sys.executable.
        import shutil as _sh
        _py_on_path = _sh.which("python") or _sh.which("python3") or "python"
        # Prefer pythonw.exe (no console) if it exists next to python.exe
        _pyw_candidate = os.path.join(os.path.dirname(_py_on_path), "pythonw.exe")
        PYTHON_EXE = _pyw_candidate if os.path.isfile(_pyw_candidate) else _py_on_path

        py_ok = subprocess.run(
            [PYTHON_EXE, "--version"], capture_output=True).returncode == 0
        if not py_ok:
            # Try bare "python" as last resort
            py_ok = subprocess.run(
                ["python", "--version"], capture_output=True).returncode == 0
            if py_ok:
                PYTHON_EXE = "python"
        if not py_ok:
            self._step(1, "warn", "Python not found — get it from python.org then rerun")
            self._log("WARNING: Download Python 3.10+ from https://python.org/downloads")
            PYTHON_EXE = "python"
        else:
            # ── Save the resolved path so Launch Now can read it reliably ──
            _cfg = os.path.join(APP_DIR, "python_path.txt")
            try:
                os.makedirs(APP_DIR, exist_ok=True)
                with open(_cfg, "w") as _f:
                    _f.write(PYTHON_EXE)
                self._log(f"Python path saved: {PYTHON_EXE}")
            except Exception as _e:
                self._log(f"Warning: could not save python path: {_e}")

            pkgs = [
                "yt-dlp", "moviepy", "piper-tts", "openai-whisper",
                "google-auth", "google-auth-oauthlib",
                "google-api-python-client", "Pillow", "requests", "numpy",
            ]
            _big = {"piper-tts", "openai-whisper", "moviepy"}
            for i, pkg in enumerate(pkgs):
                self._prog(18 + int(i / len(pkgs) * 47), f"pip install {pkg}...")
                self._log(f"  pip install {pkg}")
                _timeout = 600 if pkg in _big else 180
                r = subprocess.run(
                    [PYTHON_EXE, "-m", "pip", "install", pkg, "-q"],
                    capture_output=True, timeout=_timeout)
                self._log(f"  {'ok' if r.returncode == 0 else '!'} {pkg}")
            self._step(1, "ok", "Python packages installed")
        self._prog(65, "Packages done")

        # ── Step 2: Desktop shortcut ──────────────────────────────────────
        # Points directly to pythonw.exe — no .vbs, no .cmd, no wscript.exe
        self._step(2, "run", "Creating Desktop shortcut...")
        # Read the saved path (set a few lines above in Step 1)
        _cfg2 = os.path.join(APP_DIR, "python_path.txt")
        if os.path.isfile(_cfg2):
            python_exe = open(_cfg2).read().strip()
            if not os.path.isfile(python_exe):
                python_exe = _find_python()
        else:
            python_exe = _find_python()
        launcher = python_exe  # already prefers pythonw.exe if available
        main_py = os.path.join(APP_DIR, "src", "main.py")
        ico     = os.path.join(APP_DIR, "assets", "icon.ico")
        workdir = os.path.join(APP_DIR, "src")
        lnk     = os.path.join(DESKTOP, "Reaction Studio.lnk")

        _create_shortcut(
            lnk_path    = lnk,
            target_exe  = launcher,
            args        = f'"{main_py}"',
            workdir     = workdir,
            icon_path   = ico,
            description = "Reaction Studio — Local AI Reaction Video Generator",
        )
        self._step(2, "ok", "Desktop shortcut created")
        self._log(f"Shortcut: {lnk}")
        self._log(f"  → python.exe \"{main_py}\"")
        self._prog(80, "Shortcut done")

        # ── Step 3: Start Menu ────────────────────────────────────────────
        self._step(3, "run", "Adding to Start Menu...")
        os.makedirs(START_MENU, exist_ok=True)
        sm_lnk = os.path.join(START_MENU, "Reaction Studio.lnk")
        _create_shortcut(
            lnk_path    = sm_lnk,
            target_exe  = launcher,
            args        = f'"{main_py}"',
            workdir     = workdir,
            icon_path   = ico,
            description = "Reaction Studio — Local AI Reaction Video Generator",
        )
        self._step(3, "ok", "Added to Start Menu")
        self._log(f"Start Menu: {START_MENU}")
        self._prog(90, "Start Menu done")

        # ── Step 4: Registry (Add/Remove Programs) ────────────────────────
        self._step(4, "run", "Registering in Add/Remove Programs...")
        try:
            import winreg
            rk = winreg.CreateKey(
                winreg.HKEY_CURRENT_USER,
                r"Software\Microsoft\Windows\CurrentVersion\Uninstall\ReactionStudio")
            winreg.SetValueEx(rk, "DisplayName",     0, winreg.REG_SZ,    "Reaction Studio")
            winreg.SetValueEx(rk, "DisplayVersion",  0, winreg.REG_SZ,    "1.6")
            winreg.SetValueEx(rk, "Publisher",       0, winreg.REG_SZ,    "Reaction Studio")
            winreg.SetValueEx(rk, "InstallLocation", 0, winreg.REG_SZ,    APP_DIR)
            winreg.SetValueEx(rk, "DisplayIcon",     0, winreg.REG_SZ,    f"{ico},0")
            winreg.SetValueEx(rk, "NoModify",        0, winreg.REG_DWORD, 1)
            winreg.CloseKey(rk)
            self._step(4, "ok", "Registered in Add/Remove Programs")
        except Exception as e:
            self._step(4, "warn", f"Registry (non-critical): {e}")

        self._prog(100, "Installation complete! ✓")
        self._log("--- INSTALLATION COMPLETE ---")
        self._log(f"App folder: {APP_DIR}")
        self._log("Desktop:    Reaction Studio shortcut ready")
        self._log("Launcher:   python.exe (CREATE_NO_WINDOW)")
        self._log("OPTIONAL:   Install Ollama → https://ollama.com  then: ollama pull llama3")
        self._log("OPTIONAL:   ffmpeg → https://ffmpeg.org/download.html")

        self._done = True
        self._ui(lambda: (
            self._titlelbl.config(text="Installation Complete! ✓"),
            self._sublbl.config(
                text="Launch Reaction Studio from your Desktop or Start Menu."),
            self._btngo.config(text="  ▶  Launch Now  ", bg=GREEN, state="normal"),
            self._btnx.config(state="normal"),
        ))


if __name__ == "__main__":
    app = App()
    app.mainloop()
